# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_path": "00_encoder.ipynb",
         "train_data": "00_encoder.ipynb",
         "test_data": "00_encoder.ipynb",
         "sample_submission": "00_encoder.ipynb"}

modules = ["encoder.py",
           "decoder.py"]

doc_url = "https://mrdbarros.github.io/gquest_nbdev/"

git_url = "https://github.com/mrdbarros/gquest_nbdev/tree/master/"

def custom_doc_links(name): return None
