# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_path": "01_decoder.ipynb",
         "train_data": "01_decoder.ipynb",
         "test_data": "01_decoder.ipynb",
         "sample_submission": "01_decoder.ipynb",
         "target_columns": "01_decoder.ipynb",
         "text_columns": "01_decoder.ipynb",
         "splits": "01_decoder.ipynb",
         "df_tokenized,token_count": "01_decoder.ipynb",
         "x_tfms": "01_decoder.ipynb",
         "dbunch": "01_decoder.ipynb",
         "#dbunch.show_batch(max_n": "01_decoder.ipynb",
         "#learn": "01_decoder.ipynb",
         "learn": "01_decoder.ipynb",
         "text_regression_learner": "01_decoder.ipynb",
         "seed_all": "fastai_v1_transformers-BWW.ipynb",
         "MODEL_CLASSES": "fastai_v1_transformers-BWW.ipynb",
         "TransformersBaseTokenizer": "fastai_v1_transformers-BWW.ipynb",
         "Tokenizer_MultiColumn": "fastai_v1_transformers-BWW.ipynb",
         "TransformersVocab": "fastai_v1_transformers-BWW.ipynb",
         "SortSampler_Stateful": "fastai_v1_transformers-BWW.ipynb",
         "SortishSampler_Stateful": "fastai_v1_transformers-BWW.ipynb",
         "TokenizeProcessorDualBert": "fastai_v1_transformers-BWW.ipynb",
         "TabularDataBunch_Sample": "fastai_v1_transformers-BWW.ipynb",
         "TabularList_Sample": "fastai_v1_transformers-BWW.ipynb",
         "ExactSampler": "fastai_v1_transformers-BWW.ipynb",
         "no_collate": "fastai_v1_transformers-BWW.ipynb",
         "TextClasDataBunch_Multi": "fastai_v1_transformers-BWW.ipynb",
         "TextList_Multi": "fastai_v1_transformers-BWW.ipynb",
         "MixedObjectDataBunch": "fastai_v1_transformers-BWW.ipynb",
         "MixedObjectLists": "fastai_v1_transformers-BWW.ipynb",
         "MixedObjectList": "fastai_v1_transformers-BWW.ipynb",
         "LabelList_Multi": "fastai_v1_transformers-BWW.ipynb",
         "LabelLists_Multi": "fastai_v1_transformers-BWW.ipynb",
         "TabularModel_NoCat": "fastai_v1_transformers-BWW.ipynb",
         "CustomTransformerModel": "fastai_v1_transformers-BWW.ipynb",
         "AvgSpearman": "fastai_v1_transformers-BWW.ipynb",
         "AvgSpearman2": "fastai_v1_transformers-BWW.ipynb",
         "AddExtraBunch": "fastai_v1_transformers-BWW.ipynb",
         "FlattenedLoss_BWW": "fastai_v1_transformers-BWW.ipynb",
         "CrossEntropyFlat_BWW": "fastai_v1_transformers-BWW.ipynb",
         "model_unfreezing_and_training": "fastai_v1_transformers-BWW.ipynb",
         "get_preds_as_nparray": "fastai_v1_transformers-BWW.ipynb"}

modules = ["encoder.py",
           "decoder.py",
           "fastai_huggingface.py"]

doc_url = "https://mrdbarros.github.io/gquest_nbdev/"

git_url = "https://github.com/mrdbarros/gquest_nbdev/tree/master/"

def custom_doc_links(name): return None
