# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"testeFunc": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/mrdbarros/gquest_nbdev/tree/master/"


def custom_doc_links(name): return None
