# AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['testeFunc']

# Cell
import nltk
nltk.download('stopwords')

# Cell
def testeFunc(message):
    "doc string test"
    return(f'The test message is: {message}')