# AUTOGENERATED! DO NOT EDIT! File to edit: 00_encoder.ipynb (unless otherwise specified).

__all__ = ['data_path', 'train_data', 'test_data', 'sample_submission']

# Cell
import pandas as pd # package for high-performance, easy-to-use data structures and data analysis
import numpy as np # fundamental package for scientific computing with Python
import matplotlib
import matplotlib.pyplot as plt # for plotting

import re

import string
import gc

from fastai2.basics import *
from fastai2.text.all import *
from fastai2.callback.all import *

# Cell
import os
print(os.listdir("../data/gquest_data/"))
data_path = Path("../data/gquest_data/")

# Cell
print('Reading data...')
train_data = pd.read_csv(data_path/'train/train.csv')
test_data = pd.read_csv(data_path/'test/test.csv')
sample_submission = pd.read_csv(str(data_path/'sample_submission.csv'))
print('Reading data completed')

# Cell
print('Size of train_data', train_data.shape)
print('Size of test_data', test_data.shape)
print('Size of sample_submission', sample_submission.shape)
test_eq(train_data.shape,(6079,41))
test_eq(test_data.shape,(476,11))
test_eq(sample_submission.shape,(476,31))